name: build

on:
  push:
    branches: [ "master", "preparation" ]
  pull_request:
    branches: [ "master", "preparation" ]
  workflow_dispatch:

jobs:
  semgrep:
    name: semgrep
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
    - name: FetchSourceCode
      uses: actions/checkout@v3
    - name: Semgrep
      run: semgrep ci --config=auto --sarif --output=semgrep.sarif || true
    - name: Upload
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: semgrep.saif
      if: always()
