name: build

on:
  push:
    branches: [ "master", "preparation" ]
  pull_request:
    branches: [ "master", "preparation" ]
  workflow_dispatch:

jobs:
  semgrep:
    name: semgrep
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    step:
    -name: Semgrep 
     run: semgrep ci --config=auto
